### ISSUE TITLE
Request for new Hackage release

### ISSUE THREAD

**Issue by dynamicboid** [tclem/twirp-haskell#26] opened 2022-11-10 18:59 UTC
Would you be able to do a new release of `twirp` on Hackage? It would be really cool if we could avail of all the latest commits that have been brought in since the last release.

**Comment by neilmayhew** [comment] 2022-11-30 19:55
Any chance of moving this forward, please?

**Comment by tclem** [comment] 2022-11-30 22:15
@patrickt was going to take a look.

I'm not able to prioritize this right now so would recommend targeting source if you need the latest.

**Comment by neilmayhew** [comment] 2022-11-30 23:44
Thanks. We were wanting to purge all of our source deps in favor of Hackage ones and this is the last one!

**Comment by patrickt** [comment] 2022-12-04 15:12
Working on this today.

**Comment by dynamicboid** [comment] 2022-12-04 21:13
Thanks so much! :heart:

**Comment by neilmayhew** [comment] 2022-12-20 22:45
Do you have an ETA for this, please?

**Comment by patrickt** [comment] 2022-12-29 21:07
Ugh, sorry, I dropped the ball on this one. I seem to remember encountering dependency problems upstream when building with 9.4. I’m going to try to get to it this week. Please accept my apologies.

**Comment by neilmayhew** [comment] 2022-12-29 22:22
It looks like the problem is with 8.2, not 9.4. I recommend you change the CI settings not to fail the whole matrix if any individual build fails. If 8.2 ends up being the only one that falls, you could just drop it from the matrix.

Even though the project was building previously with 8.2, the problem now is that 8.2 isn't installable.

**Comment by patrickt** [comment] 2023-01-04 13:48
For various dependency reasons (I would really like for the next release to build with 9.4), I think I need to do https://github.com/tclem/twirp-haskell/issues/28 first.

**Comment by patrickt** [comment] 2023-01-04 13:49
https://github.com/tclem/proto-lens-jsonpb/pull/13 is the first part of this.

**Comment by patrickt** [comment] 2023-01-04 14:10
https://github.com/tclem/twirp-haskell/pull/29 is the second.

**Comment by patrickt** [comment] 2023-01-06 16:46
0.2.2 is released. Very sorry for the delay. We’re no longer using this library in production, so if someone else wants to pick up commit bits/Hackage upload rights, we’d be happy to hand them out.

**Closed as completed by patrickt** 2023-01-06 16:46 UTC

**Comment by dynamicboid** [comment] 2023-01-11 17:38
Thanks so much for taking the time to do the release, Patrick!

**Comment by neilmayhew** [comment] 2023-01-14 03:21
I'm interested in helping to maintain this project, so I'd welcome having the necessary permissions.

My Hackage username is NeilMayhew.
